services:
  gigachess.api:
    build:
      context: .
      dockerfile: "GigaChess.Api/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7130:8080"
        
  gigachess.frontend:
    build:
      context: .
      dockerfile: "GigaChess.Frontend/Dockerfile"
    ports:
      - "8080:8080"